# Generated by Django 4.2 on 2023-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=888)),
                ('Email', models.EmailField(default='null', max_length=888)),
                ('Phonenumber', models.CharField(default='null', max_length=888)),
            ],
        ),
    ]
