# Generated by Django 4.2 on 2023-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Email',
            field=models.EmailField(max_length=888),
        ),
        migrations.AlterField(
            model_name='book',
            name='Phonenumber',
            field=models.CharField(max_length=888),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=888),
        ),
    ]
